### ISSUE TITLE
Build failed on Raspberry Pi

### ISSUE THREAD

**Issue by rocky1201** [camme/node-nfc#1]
I got these errors while building on R-Pi:
../src/nfc.cc:73:68: error: invalid conversion from ‘void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}’ to ‘uv_after_work_cb {aka void (*)(uv_work_s*, int)}’ [-fpermissive]
/home/pi/.node-gyp/0.10.12/deps/uv/include/uv.h:1432:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
../src/nfc.cc: In function ‘void {anonymous}::Loop({anonymous}::Baton*)’:
../src/nfc.cc:85:68: error: invalid conversion from ‘void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}’ to ‘uv_after_work_cb {aka void (*)(uv_work_s*, int)}’ [-fpermissive]
/home/pi/.node-gyp/0.10.12/deps/uv/include/uv.h:1432:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
../src/nfc.cc: In function ‘void {anonymous}::NFCRead(uv_work_t*)’:
../src/nfc.cc:95:13: error: expected primary-expression before ‘.’ token
../src/nfc.cc:96:13: error: expected primary-expression before ‘.’ token
../src/nfc.cc: In function ‘void {anonymous}::AfterNFCRead(uv_work_t*)’:
../src/nfc.cc:129:59: error: ‘memcpy’ was not declared in this scope

**Comment by jeroenvollenbrock** [comment]
Is this problem still existent in 0.3.1?
