### ISSUE TITLE
Use Nan for later version compatibility

### ISSUE THREAD

**Issue by sdumetz** [camme/node-nfc#19]
To keep things simple it's advised to use [NAN](https://www.npmjs.com/package/nan) which will abstract all the API changes between node versions. this will allow the module to be compatible with node 0.10 to 5.x.

I can work with you on this if you want to implement it.

**Comment by jeroenvollenbrock** [comment]
It's already implemented in the version on github. It's just not published to npm. See #8

**Comment by sdumetz** [comment]
OK. Closing this then. Thanks.
