### ISSUE TITLE
Update for newer Node.js v.6.x.x

### ISSUE THREAD

**Issue by TemaSM** [camme/node-nfc#26]
Hi! :smiley: 

How about to update `node-nfc` to newer version of Node.js?

I tested it on v.6.1.0 and v.6.2.2 - while building by `node-gyp`, it goes to errors, and that's because of using old (2.0.5) version of `nan`(current is 2.3.5).
After I manually updated `nan` and rebuilded `node-nfc` for Node v.6.1.0 - it's wroking, but I guess that we need to update native source of `node-nfc` to work with newer `nan`(2.3.5), because on builidng stage there is one error occurs:
```bash
../src/nfc.cc: In member function ‘virtual void {anonymous}::NFCReadWorker::HandleErrorCallback()’:
../src/nfc.cc:153:70: warning: array subscript is above array bounds [-Warray-bounds]
             argv[1] = Nan::Error(AsyncProgressWorker::ErrorMessage());
```
-
P.S> I gonna use `node-nfc` as native module for Atom Electron 1.2.5 (Node.js v6.1.0).
UPD: I updated `node-nfc` to Node.js v.6.1.0 and builded it for Electron 1.2.5 and it's working fine.

**Comment by jeroenvollenbrock** [comment]
Fixed in 0.3.3
