### ISSUE TITLE
.on('read') returns after awhile

### ISSUE THREAD

**Issue by jaredallard** [camme/node-nfc#28]
So, using 0.3.3, with `acr122u`. If I keep tapping the card it'll stay up, otherwise it times out after inactivity. Anyway to fix this?

**Comment by jaredallard** [comment]
Using `node-pcsclite` with `simple-pcsc` for now, awesome project though :)

**Comment by tournevis** [comment]
Hey,
I got the same issue using also an acr122u . I have 3 NFC readers exactly like this one [https://www.amazon.fr/dp/B00VSMQSDW](url) . I tested them on a raspberry 3, with raspbian and the example script. If I keep the tag on the device,  no problems ( it logs tag info continuously ) , but if I remove it , the script stop  a few seconds after 

Two of them logs different errors before quit : 

 The first one : 

![image](https://cloud.githubusercontent.com/assets/8899117/20136276/319ef1a4-a674-11e6-8bed-6d1fcc4a13ca.png)

 The second : 

![image](https://cloud.githubusercontent.com/assets/8899117/20136284/3cf37c82-a674-11e6-9e95-a35245cbbea2.png)

Anyway to fix this ?

**Comment by spathon** [comment]
I have similar issues with PN532.
And no way of catching it so I can restart
