### ISSUE TITLE
Error While installation

### ISSUE THREAD

**Issue by S0c5** [camme/node-nfc#3]
I have this error while i try install node nfc 

 make: Entering directory `/usr/local/lib/node_modules/nfc/build'
 CXX(target) Release/obj.target/nfc/src/nfc.o
../src/nfc.cc:29:9: error: ‘nfc_device’ does not name a type
../src/nfc.cc:30:9: error: ‘nfc_target’ does not name a type
../src/nfc.cc:31:9: error: ‘nfc_context’ does not name a type
../src/nfc.cc: In static member function ‘static v8::Handle<v8::Value> {anonymous}::NFC::Start(const v8::Arguments&)’:
../src/nfc.cc:42:9: error: ‘nfc_device’ was not declared in this scope
../src/nfc.cc:42:21: error: ‘pnd’ was not declared in this scope
../src/nfc.cc:43:9: error: ‘nfc_target’ was not declared in this scope
../src/nfc.cc:43:20: error: expected ‘;’ before ‘nt’
../src/nfc.cc:44:9: error: ‘nfc_context’ was not declared in this scope
../src/nfc.cc:44:22: error: ‘context’ was not declared in this scope

do you know why happen that error?

**Comment by jeroenvollenbrock** [comment]
Quite a late answer, but are you sure you had libnfc-dev installed?

**Comment by jeroenvollenbrock** [comment]
Looks like libnfc wasn't installed, closing due to lack of response.
